export default {
    CREATED: 'CREATED',
    CREATING: 'CREATING',
    QUOTED: 'QUOTED',
    QUOTEING: 'QUOTEING',
    ACCEPTED: 'ACCEPTED',
    ACCEPTING: 'ACCEPTING',
    FINISHED: 'FINISHED',
    FINISHING: 'FINISHING',
    PAYED: 'PAYED',
};
